#!/usr/bin/env bash
set -euo pipefail

REPO_RAW="https://raw.githubusercontent.com/imartinstudio/cover-prompt-skills/main"
INSTALL_INDEX_URL="$REPO_RAW/generated/install-index.sh"
TARGET_DIR="${COVER_SKILLS_TARGET:-$HOME/.shared-skills}"
BACKUP_DIR="${COVER_SKILLS_BACKUP_DIR:-$TARGET_DIR/.cover-prompt-skills-backup}"
REMOTE_INSTALL_INDEX=""
SCRIPT_PATH="${BASH_SOURCE[0]:-}"
SCRIPT_DIR=""

if [[ -n "$SCRIPT_PATH" && -f "$SCRIPT_PATH" ]]; then
  SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd -P)"
fi

cleanup_remote_install_index() {
  if [[ -n "$REMOTE_INSTALL_INDEX" && -f "$REMOTE_INSTALL_INDEX" ]]; then
    rm -f "$REMOTE_INSTALL_INDEX"
  fi
}

trap cleanup_remote_install_index EXIT

has_local_project() {
  [[ -n "$SCRIPT_DIR" && -d "$SCRIPT_DIR/plugins" && -x "$SCRIPT_DIR/scripts/install.sh" ]]
}

backup_existing_target() {
  local name="$1" dst="$2" stamp backup
  stamp="$(date +%Y%m%d%H%M%S)"
  backup="$BACKUP_DIR/$stamp/$name"
  mkdir -p "$(dirname "$backup")"
  mv "$dst" "$backup"
  echo "Backed up: $dst -> $backup"
}

install_from_local() {
  COVER_SKILLS_TARGET="$TARGET_DIR" "$SCRIPT_DIR/scripts/install.sh" "$@"
}

load_remote_inventory() {
  REMOTE_INSTALL_INDEX="$(mktemp "${TMPDIR:-/tmp}/cover-prompt-skills-install-index.XXXXXX")"
  if ! curl -fsSL "$INSTALL_INDEX_URL" -o "$REMOTE_INSTALL_INDEX"; then
    echo "Failed to download generated install inventory: $INSTALL_INDEX_URL" >&2
    exit 1
  fi
  parse_remote_install_index "$REMOTE_INSTALL_INDEX"
}

parse_remote_install_index() {
  local index_path="$1"
  local line line_number=0 section="" skill
  local all_seen=0 base_seen=0 with_docs_seen=0 cover_tips_seen=0
  local skill_line_re='^  "([a-z0-9]+(-[a-z0-9]+)*)"$'

  ALL_SKILLS=()
  BASE_SKILLS=()
  WITH_DOCS_SKILLS=()

  array_contains() {
    local candidate="$1"
    shift
    local existing
    for existing in "$@"; do
      if [[ "$existing" == "$candidate" ]]; then
        return 0
      fi
    done
    return 1
  }

  while IFS= read -r line || [[ -n "$line" ]]; do
    ((line_number += 1))

    if [[ -z "$line" || "$line" == "#!/usr/bin/env bash" || \
      "$line" == "# Generated by scripts/skill_registry.py; do not edit by hand." || \
      "$line" == "# shellcheck shell=bash" ]]; then
      if [[ -n "$section" ]]; then
        echo "Invalid generated install inventory at line $line_number: unexpected blank/comment" >&2
        return 1
      fi
      continue
    fi

    case "$line" in
      "ALL_SKILLS=(")
        if [[ -n "$section" || "$all_seen" -eq 1 ]]; then
          echo "Invalid generated install inventory at line $line_number: duplicate or nested ALL_SKILLS" >&2
          return 1
        fi
        section="ALL_SKILLS"
        all_seen=1
        continue
        ;;
      "BASE_SKILLS=(")
        if [[ -n "$section" || "$base_seen" -eq 1 ]]; then
          echo "Invalid generated install inventory at line $line_number: duplicate or nested BASE_SKILLS" >&2
          return 1
        fi
        section="BASE_SKILLS"
        base_seen=1
        continue
        ;;
      "WITH_DOCS_SKILLS=(")
        if [[ -n "$section" || "$with_docs_seen" -eq 1 ]]; then
          echo "Invalid generated install inventory at line $line_number: duplicate or nested WITH_DOCS_SKILLS" >&2
          return 1
        fi
        section="WITH_DOCS_SKILLS"
        with_docs_seen=1
        continue
        ;;
      ")")
        if [[ -z "$section" ]]; then
          echo "Invalid generated install inventory at line $line_number: unexpected array close" >&2
          return 1
        fi
        section=""
        continue
        ;;
      'COVER_TIPS_SKILL="cover-tips"')
        if [[ -n "$section" || "$cover_tips_seen" -eq 1 ]]; then
          echo "Invalid generated install inventory at line $line_number: duplicate or nested COVER_TIPS_SKILL" >&2
          return 1
        fi
        cover_tips_seen=1
        continue
        ;;
    esac

    if [[ -n "$section" ]]; then
      if [[ "$line" =~ $skill_line_re ]]; then
        skill="${BASH_REMATCH[1]}"
        case "$section" in
          ALL_SKILLS)
            if [[ ${#ALL_SKILLS[@]} -gt 0 ]] && array_contains "$skill" "${ALL_SKILLS[@]}"; then
              echo "Invalid generated install inventory at line $line_number: duplicate ALL_SKILLS entry" >&2
              return 1
            fi
            ALL_SKILLS+=("$skill")
            ;;
          BASE_SKILLS)
            if [[ ${#BASE_SKILLS[@]} -gt 0 ]] && array_contains "$skill" "${BASE_SKILLS[@]}"; then
              echo "Invalid generated install inventory at line $line_number: duplicate BASE_SKILLS entry" >&2
              return 1
            fi
            BASE_SKILLS+=("$skill")
            ;;
          WITH_DOCS_SKILLS)
            if [[ ${#WITH_DOCS_SKILLS[@]} -gt 0 ]] && array_contains "$skill" "${WITH_DOCS_SKILLS[@]}"; then
              echo "Invalid generated install inventory at line $line_number: duplicate WITH_DOCS_SKILLS entry" >&2
              return 1
            fi
            WITH_DOCS_SKILLS+=("$skill")
            ;;
          *)
            echo "Invalid generated install inventory at line $line_number: unknown array" >&2
            return 1
            ;;
        esac
        continue
      fi
      echo "Invalid generated install inventory at line $line_number: unsafe skill name or malformed line" >&2
      return 1
    fi

    echo "Invalid generated install inventory at line $line_number: unrecognized line" >&2
    return 1
  done < "$index_path"

  if [[ -n "$section" || "$all_seen" -eq 0 || "$base_seen" -eq 0 || \
    "$with_docs_seen" -eq 0 || "$cover_tips_seen" -eq 0 ]]; then
    echo "Invalid generated install inventory: incomplete allowlisted structure" >&2
    return 1
  fi
  if [[ ${#ALL_SKILLS[@]} -eq 0 ]]; then
    echo "Invalid generated install inventory: ALL_SKILLS is empty" >&2
    return 1
  fi
  if [[ ${#BASE_SKILLS[@]} -eq 0 || ${#WITH_DOCS_SKILLS[@]} -eq 0 ]]; then
    echo "Invalid generated install inventory: base/with-docs sections are incomplete" >&2
    return 1
  fi

  local base_skill with_docs_skill found
  for base_skill in "${BASE_SKILLS[@]}"; do
    if [[ "$base_skill" == *-with-docs || "$base_skill" == "cover-tips" ]]; then
      echo "Invalid generated install inventory: invalid BASE_SKILLS entry: $base_skill" >&2
      return 1
    fi
    if ! is_known_skill "$base_skill"; then
      echo "Invalid generated install inventory: BASE_SKILLS entry is not in ALL_SKILLS: $base_skill" >&2
      return 1
    fi
  done
  for with_docs_skill in "${WITH_DOCS_SKILLS[@]}"; do
    if [[ "$with_docs_skill" != *-with-docs ]]; then
      echo "Invalid generated install inventory: invalid WITH_DOCS_SKILLS entry: $with_docs_skill" >&2
      return 1
    fi
    if ! is_known_skill "$with_docs_skill"; then
      echo "Invalid generated install inventory: WITH_DOCS_SKILLS entry is not in ALL_SKILLS: $with_docs_skill" >&2
      return 1
    fi
  done
  for skill in "${ALL_SKILLS[@]}"; do
    if [[ "$skill" == "cover-tips" ]]; then
      continue
    fi
    found=0
    if array_contains "$skill" "${BASE_SKILLS[@]}" || array_contains "$skill" "${WITH_DOCS_SKILLS[@]}"; then
      found=1
    fi
    if [[ "$found" -eq 0 ]]; then
      echo "Invalid generated install inventory: ALL_SKILLS entry is not classified: $skill" >&2
      return 1
    fi
  done
}

is_known_skill() {
  local candidate="$1"
  local skill
  for skill in "${ALL_SKILLS[@]}"; do
    if [[ "$skill" == "$candidate" ]]; then
      return 0
    fi
  done
  return 1
}

install_skill_remote() {
  local name="$1"
  local src_url="$REPO_RAW/plugins/$name/skills/$name/SKILL.md"
  local dst="$TARGET_DIR/$name"

  if ! is_known_skill "$name"; then
    echo "Skill is not in the generated inventory: $name" >&2
    exit 1
  fi

  echo "Downloading $name..."

  mkdir -p "$TARGET_DIR"

  if [[ -L "$dst" ]]; then
    rm "$dst"
  elif [[ -d "$dst" ]]; then
    backup_existing_target "$name" "$dst"
  fi

  mkdir -p "$dst"
  if ! curl -fsSL "$src_url" -o "$dst/SKILL.md"; then
    echo "Failed to download: $name" >&2
    rm -rf "$dst"
    return 1
  fi
  echo "Installed: $name -> $dst"
}

main() {
  if has_local_project; then
    install_from_local "$@"
    return
  fi

  load_remote_inventory

  local requested=("$@")
  if [[ ${#requested[@]} -eq 0 || "${requested[0]}" == "cover" || "${requested[0]}" == "all" ]]; then
    requested=("${ALL_SKILLS[@]}")
  fi

  for skill in "${requested[@]}"; do
    install_skill_remote "$skill"
  done

  local try_command="\$cover-tips 撕纸剪贴"
  if [[ $# -gt 0 && "${1:-}" != "cover" && "${1:-}" != "all" ]]; then
    if [[ "$*" != *"cover-tips"* ]]; then
      try_command="\$${1}"
    fi
  fi

  cat <<EOF

Done.

Installed skills target:
  $TARGET_DIR

Try:
  $try_command

  主题：可以洗稿，但不能被洗脑
  副标题：AI 时代的内容判断力
  用途：X封面
EOF
}

main "$@"
